// Code generated by goctl. DO NOT EDIT.
// Source: user.sys.proto

package server

import (
	"context"

	"lanshan/class11/user/rpc/internal/logic"
	"lanshan/class11/user/rpc/internal/svc"
	"lanshan/class11/user/rpc/pb/user"
)

type SysServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedSysServer
}

func NewSysServer(svcCtx *svc.ServiceContext) *SysServer {
	return &SysServer{
		svcCtx: svcCtx,
	}
}

func (s *SysServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterRes, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *SysServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginRes, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
